name: TeleportSuite
main: net.krinsoft.teleportsuite.TeleportSuite
version: maven-version-number
author: krinsdeath
load: STARTUP
api-version: 1.13

commands:
  #####################
  # teleport commands #
  #####################
  teleport:
    aliases: [tps]
    description: The basic command and root for all TeleportSuite commands.
    usage: /<command> [options]...
  tpa:
    description: Allows users to request a teleport to another player.
    usage: /<command> [player]
  tpahere:
    description: Allows users to request another user teleport to them.
    usage: /<command> [player]
  tp:
    description: Allows users to teleport directly to another player.
    usage: /<command> [player]
  tphere:
    description: Allows users to teleport a user directly to them.
    usage: /<command> [player]
  tpo:
    description: Teleports the sender directly to the target, regardless of their status.
    usage: /<command> [player]
  tpohere:
    description: Teleports the target directly to the sender, regardless of their status.
    usage: /<command> [player]
  tpm:
    description: Teleports one player to another using /tpa, but bypassing permissions.
    usage: /<command> [player from] [player to]
  tpmhere:
    description: Teleports one player to another using /tpahere, but bypassing permissions.
    usage: /<command> [player from] [player to]
  tpworld:
    aliases: [world, tpw]
    description: Teleports to your last known location in the specified world.
    usage: /<command> [world] [-s]
  tpback:
    aliases: [back, tpb]
    description: Teleports the sender to their location prior to their last teleport.
    usage: /<command>
  tprewind:
    aliases: [rewind, tprew]
    description: |
      Rewinds a specified number of teleports for the target user.
      Maximum set by config.yml (default 5)
      Usable from Console
    usage: /<command> [target] [val]
  tplocation:
    aliases: [location, tploc, loc]
    description: Teleports the sender to a specific location
    usage: /<command> x y z [world]
  #################
  # user commands #
  #################
  tpaccept:
    aliases: [accept, tpacc, acc]
    description: |
      Accepts an active teleport request from the specified player,
      or all active requests.
    usage: /<command> [request] [-all]
  tpreject:
    aliases: [reject, tprej, rej]
    description: |
      Rejects an active teleport request from the specified player,
      or all active requests.
    usage: /<command> [request] [-all]
  tpcancel:
    aliases: [cancel, tpcan, can]
    description: Cancels your currently active request.
    usage: /<command>
  tprequests:
    aliases: [requests, tpreq, req]
    description: |
      Lists your active requests and any pending requests.
      Usable from Console
    usage: /<command> [target]
  tptoggle:
    aliases: [toggle, tptog, tog]
    description: |
      Toggles your 'request' status.
      "Accepting" means you will be prompted to accept any requests
      "Rejecting" means you will ignore all requests
      "Auto" means you will automatically accept all requests
    usage: /<command> [OPTION]
  tpsilent:
    aliases: [silent, tpsil]
    description: |
      Toggle. Makes your teleports silent (no broadcast).
      Applies only to tpo and tpohere.
    usage: /<command>
  tpcoords:
    aliases: [coords, tpco]
    description: Shows the sender their current location
    usage: /<command>
  tplang:
    description: Allows a user to set their language.
    usage: /<command> [language]
  ###########################
  # administrative commands #
  ###########################
  tpdebug:
    description: Toggles debug mode for TeleportSuite.
    usage: /<command>
  tpreload:
    description: Reloads TeleportSuite's configuration files.
    usage: /<command>
  # legacy vanilla /tp
  tpvanilla:
    aliases: [vanilla, tpv]
    description: |
      Teleports the first player to the second player.
      Usable from Console
    usage: /<command> [player from] [player to]
  # warp commands
  # coming soon!

permissions:
  teleport.economy.bypass:
    description: Allows the user to bypass economy costs for teleports.
  teleport.users:
    children:
      teleport.tpa: true
      teleport.tpahere: true
      teleport.accept: true
      teleport.reject: true
      teleport.cancel: true
      teleport.toggle: true
      teleport.requests: true
      teleport.coords: true
      teleport.back: true
      teleport.world: true
      teleport.world.*: true
  teleport.mods:
    children:
      teleport.users: true
      teleport.tp: true
      teleport.tphere: true
      teleport.tp.other: true
      teleport.vanilla: true
      teleport.location: true
  teleport.admins:
    children:
      teleport.mods: true
      teleport.silent: true
      teleport.rewind: true
      teleport.tpo: true
      teleport.tpohere: true